DeVeeraApp/ViewModels/LayoutSetups/LayoutSetupModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;



namespace DeVeeraApp.ViewModels.LayoutSetups
{
    public class LayoutSetupModel:BaseEntityModel
    {

        public LayoutSetupModel()
        {
            AvailableImages = new List<SelectListItem>();
            AvailableVideo = new List<SelectListItem>();
        }

      

        //User Dashboard
        [DataType(DataType.ImageUrl)]
        [Required(ErrorMessage ="Select slider 1 image")]

        public int SliderOneImageId { get; set; }


        [Required(ErrorMessage = "Select slider 2 image")]
        public int SliderTwoImageId { get; set; }


        [Required(ErrorMessage = "Select slider 3 image")]
        public int SliderThreeImageId { get; set; }
        public string SliderOneImageUrl { get; set; }
        public string SliderTwoImageUrl { get; set; }
        public string SliderThreeImageUrl { get; set; }

        //[Required(ErrorMessage = "Please enter slider 1 title")]
        public string SliderOneTitle { get; set; }
        public string SliderOneDescription { get; set; }
        //[Required(ErrorMessage = "Please enter slider 2 title")]
        public string SliderTwoTitle { get; set; }
        public string SliderTwoDescription { get; set; }
        //[Required(ErrorMessage = "Please enter slider 3 title")]
        public string SliderThreeTitle { get; set; }
        public string SliderThreeDescription { get; set; }
        public bool IsActive { get; set; }

        //User Registration Form
        public int BannerOneImageId { get; set; }
        public string BannerOneImageUrl { get; set; }

        //User Login Form
        public int BannerTwoImageId { get; set; }
        public string BannerTwoImageUrl { get; set; }

        //User Diary
        public int DiaryHeaderImageId { get; set; }
        public string DiaryHeaderImageUrl { get; set; }

        //Complete Registration from
        public int CompleteRegistrationHeaderImgId { get; set; }
        public string CompleteRegistrationHeaderImgUrl { get; set; }
        
       // [Required(ErrorMessage ="Enter the reason")]
        public string ReasonToSubmit { get; set; }
        public List<SelectListItem> AvailableImages { get; }

        public string Link_1 { get; set; }
        public string Link_2 { get; set; }
        public string Link_3 { get; set; }

        public int Link_1_BannerImageId { get; set; }
        public int Link_2_BannerImageId { get; set; }
        public int Link_3_BannerImageId { get; set; }

        public string Link_1_BannerImageUrl { get; set; }
        public string Link_2_BannerImageUrl { get; set; }
        public string Link_3_BannerImageUrl { get; set; }

        //Module Section Header
         public string Title { get; set; }
         public string Description { get; set; }
        public string ModuleSpanishDescription { get; set; }
        public string ModuleSpanishTitle { get; set; }

        //Home
        public string HomeTitle { get; set; }
        public string HomeDescription { get; set; }
        public string HomeSubTitle { get; set; }
        public string HomeSpanishDescription { get; set; }
        public string HomeTitleSpanish { get; set; }
        public string HomeSubTitleSpanish { get; set; }

        //video
        [Required]
        public int? VideoId { get; set; }
        public int BannerImageId { get; set; }
        public string BannerImageUrl { get; set; }

        public int VideoThumbImageId { get; set; }
        public string VideoThumbImageUrl { get; set; }

        public int ShareBackgroundImageId { get; set; }
        public string ShareBackgroundImageUrl { get; set; }
        public IList<SelectListItem> AvailableVideo { get; set; }
        //Footer 
        public string FooterDescription { get; set; }
        public string FooterDescriptionSpanish { get; set; }
        public string Email{ get; set; }
     
        public string PhoneNo{ get; set; }
         public int FooterImageId { get; set; }
          public string FooterImageUrl { get; set; }
        public string Location { get; set; }
        public string LocationSpanish { get; set; }

    }
}

DeVeeraApp/Areas/Admin/Controllers/LayoutSetupController.cs
using CRM.Core;
using CRM.Core.Domain.LayoutSetups;
using CRM.Services;
using CRM.Services.Authentication;
using CRM.Services.Layoutsetup;
using CRM.Services.Localization;
using CRM.Services.Message;
using DeVeeraApp.Filters;
using DeVeeraApp.Utils;
using DeVeeraApp.ViewModels.Common;
using DeVeeraApp.ViewModels.LayoutSetups;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using Newtonsoft.Json;
using System;

using System.Collections.Generic;
using System.Linq;

namespace DeVeeraApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AuthorizeAdmin]
    public class LayoutSetupController : BaseController
    {
        #region fields
        private readonly ILayoutSetupService _layoutSetupService;
        private readonly INotificationService _notificationService;
        private readonly IImageMasterService _imageMasterService;
        private readonly ITranslationService _translationService;
        private readonly IVideoMasterService _videoServices;
        private readonly ILocalStringResourcesServices _localStringResourcesServices;
        public string key = "AIzaSyC2wpcQiQQ7ASdt4vcJHfmly8DwE3l3tqE";
        #endregion

        #region ctor

        public LayoutSetupController(ILayoutSetupService layoutSetupService,
                                     IImageMasterService imageMasterService,
                                     INotificationService notificationService,
                                     IWorkContext workContext,
                                     IVideoMasterService videoService,
                                     IHttpContextAccessor httpContextAccessor,
                                     IAuthenticationService authenticationService,
                                      ITranslationService translationService,
                                       ILocalStringResourcesServices localStringResourcesServices) : base(workContext: workContext,
                                                                                  httpContextAccessor: httpContextAccessor,
                                                                                  authenticationService: authenticationService)

        {
            _layoutSetupService = layoutSetupService;
            _imageMasterService = imageMasterService;
            _notificationService = notificationService;
            _translationService = translationService;
            _videoServices = videoService;
            _localStringResourcesServices = localStringResourcesServices;
        }
        #endregion

        #region Utilities
        public virtual void PrepareImages(LayoutSetupModel model)
        {
            model.AvailableVideo.Add(new SelectListItem { Text = "Select Video", Value = "0" });
            var AvailableVideoUrl = _videoServices.GetAllVideos();
            foreach (var url in AvailableVideoUrl)
            {
                model.AvailableVideo.Add(new SelectListItem
                {
                    Value = url.Id.ToString(),
                    Text = url.Name,
                    Selected = url.Id == model.VideoId
                });
            }
            //prepare available images
            var AvailableImages = _imageMasterService.GetAllImages();
            foreach (var item in AvailableImages)
            {
                model.AvailableImages.Add(new SelectListItem
                {
                    Value = item.Id.ToString(),
                    Text = item.Name,
                });               
            }
        }
        public virtual void PrepareImageUrls(LayoutSetupModel model)
        {
            model.AvailableVideo.Add(new SelectListItem { Text = "Select Video", Value = "0" });
            var AvailableVideoUrl = _videoServices.GetAllVideos();
            foreach (var url in AvailableVideoUrl)
            {
                model.AvailableVideo.Add(new SelectListItem
                {
                    Value = url.Id.ToString(),
                    Text = url.Name,
                    Selected = url.Id == model.VideoId
                });
            }
            model.SliderOneImageUrl = model.SliderOneImageId>0 ? _imageMasterService.GetImageById(model.SliderOneImageId)?.ImageUrl:null;
            model.SliderTwoImageUrl = model.SliderTwoImageId > 0 ? _imageMasterService.GetImageById(model.SliderTwoImageId)?.ImageUrl : null;
            model.SliderThreeImageUrl = model.SliderThreeImageId > 0 ? _imageMasterService.GetImageById(model.SliderThreeImageId)?.ImageUrl : null;
            model.BannerOneImageUrl = model.BannerOneImageId > 0 ? _imageMasterService.GetImageById(model.BannerOneImageId)?.ImageUrl : null;
            model.BannerTwoImageUrl = model.BannerTwoImageId > 0 ? _imageMasterService.GetImageById(model.BannerTwoImageId)?.ImageUrl : null;
            model.DiaryHeaderImageUrl = model.DiaryHeaderImageId > 0 ? _imageMasterService.GetImageById(model.DiaryHeaderImageId)?.ImageUrl : null;
            model.CompleteRegistrationHeaderImgUrl = model.CompleteRegistrationHeaderImgId > 0 ? _imageMasterService.GetImageById(model.CompleteRegistrationHeaderImgId)?.ImageUrl : null;
            model.Link_1_BannerImageUrl= model.Link_1_BannerImageId > 0 ? _imageMasterService.GetImageById(model.Link_1_BannerImageId)?.ImageUrl : null;
            model.Link_2_BannerImageUrl = model.Link_2_BannerImageId > 0 ? _imageMasterService.GetImageById(model.Link_2_BannerImageId)?.ImageUrl : null;
            model.Link_3_BannerImageUrl = model.Link_3_BannerImageId > 0 ? _imageMasterService.GetImageById(model.Link_3_BannerImageId)?.ImageUrl : null;
            model.FooterImageUrl = model.FooterImageId > 0 ? _imageMasterService.GetImageById(model.FooterImageId)?.ImageUrl : null;
        }

        #endregion

            public IActionResult Index()
        {
            return View();
        }
        public IActionResult List()
        {
            AddBreadcrumbs("Layout Setup", "List", "/Admin/LayoutSetup/List", "/Admin/LayoutSetup/List");
            var model = new List<LayoutSetupModel>();
            var data = _layoutSetupService.GetAllLayoutSetups();
            if (data.Count() != 0)
            {
                model = data.ToList().ToModelList<LayoutSetup, LayoutSetupModel>(model);
                ViewBag.LayOut = JsonConvert.SerializeObject(model);
                return View(model);
            }
            return View(model);
        }
        public IActionResult Create()
        {
            AddBreadcrumbs("Layout Setup", "Create", "/Admin/LayoutSetup/List", "/Admin/LayoutSetup/Create");

            LayoutSetupModel model = new LayoutSetupModel();
            PrepareImages(model);
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(LayoutSetupModel model)
        {
            AddBreadcrumbs("Layout Setup", "Create", "/LayoutSetup/Create", "/LayoutSetup/Create");

            if (ModelState.IsValid)
            {
                model.VideoId = (model.VideoId == 0) ? model.VideoId = null : model.VideoId;
                var data = model.ToEntity<LayoutSetup>();

                _layoutSetupService.InsertLayoutSetup(data);
                _translationService.Translate(model.Title, model.ModuleSpanishTitle);
                _translationService.Translate(model.Description, model.ModuleSpanishDescription);
                _translationService.Translate(model.Title, model.HomeTitleSpanish);
                _translationService.Translate(model.HomeSubTitle, model.HomeSubTitleSpanish);
                _translationService.Translate(model.Description, model.HomeSpanishDescription);
                _translationService.Translate(model.Location, model.LocationSpanish);
                _translationService.Translate(model.FooterDescription, model.FooterDescriptionSpanish);
                _notificationService.SuccessNotification("Layout Setup Successfully.");
                return RedirectToAction("List");
            }

            PrepareImages(model);
            return View(model);
        }

        public IActionResult Edit(int Id)
        {
            AddBreadcrumbs("Layout Setup", "Edit", $"/Admin/LayoutSetup/List", $"/Admin/LayoutSetup/Edit/{Id}");

            if (Id != 0)
            {
                var data = _layoutSetupService.GetLayoutSetupById(Id);
                if (data != null)
                {
                    var model = data.ToModel<LayoutSetupModel>();
                    model.BannerImageUrl = _imageMasterService.GetImageById(data.BannerImageId)?.ImageUrl;
                    model.VideoThumbImageUrl = _imageMasterService.GetImageById(data.VideoThumbImageId)?.ImageUrl;
                    model.ShareBackgroundImageUrl = _imageMasterService.GetImageById(data.ShareBackgroundImageId)?.ImageUrl;
                    model.ModuleSpanishTitle = _localStringResourcesServices.GetResourceValueByResourceNameScreen(model.Title);
                    model.ModuleSpanishDescription = _localStringResourcesServices.GetResourceValueByResourceNameScreen(model.Description);
                    model.HomeTitleSpanish = _localStringResourcesServices.GetResourceValueByResourceNameScreen(model.HomeTitle);
                    model.HomeSubTitleSpanish = _localStringResourcesServices.GetResourceValueByResourceNameScreen(model.HomeSubTitle);
                    model.HomeSpanishDescription = _localStringResourcesServices.GetResourceValueByResourceNameScreen(model.HomeDescription);
                    model.FooterDescriptionSpanish = _localStringResourcesServices.GetResourceValueByResourceNameScreen(model.FooterDescription);
                    model.LocationSpanish = _localStringResourcesServices.GetResourceValueByResourceNameScreen(model.Location);
                    PrepareImageUrls(model);
                    return View(model);
                }

            }
            return View();
        }

        [HttpPost]

DeVeeraApp/Areas/Admin/Views/LayoutSetup/List.cshtml
@model List<DeVeeraApp.ViewModels.LayoutSetups.LayoutSetupModel>
@{
    ViewData["Title"] = "List";
}

<style>
    .camelclass {
        text-transform: capitalize;
    }
</style>
@if (@ViewBag.LayOut != null)
{
    <div class="intro-y  py-10 sm:py-20 ">
        <div class="px-5 ">
            <div class="font-medium text-center text-lg"> Layout Setup List</div>
            <div class="text-gray-600 text-center mt-2 camelclass ">Below are the list of layout setup.</div>
        </div>

        <div class="px-5 sm:px-20  border-t border-gray-200 dark:border-dark-5">
            <div class="grid grid-cols-12 mt-6">
                <div class="intro-y col-span-12 text-right">
                    <a asp-controller="LayoutSetup" asp-action="Create" class="btn btn-primary w-28"><i data-feather="plus" class="mr-2 w-5 h-5"></i>Create</a>
                </div>
            </div>
            @*<div class="grid grid-cols-12 gap-4 gap-y-5 mt-6">
                    <div class="intro-y box p-5 col-span-12">
                        <div class="intro-y">

                            <div class="p-5" id="basic-table">
                                <div class="preview">
                                    <div class="overflow-x-auto">
                                        <table class="table">
                                            <thead>
                                                <tr>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">#</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Title 1</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Title 2</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Title 3</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Edit</th>
                                                    <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Delete</th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                                @{
                                                    int i = 1;
                                                    foreach (var item in Model)
                                                    {
                                                        <tr>
                                                            <td class="border-b dark:border-dark-5">@i</td>
                                                            <td class="border-b dark:border-dark-5">@item.SliderOneTitle</td>
                                                            <td class="border-b dark:border-dark-5">@item.SliderTwoTitle</td>
                                                            <td class="border-b dark:border-dark-5">@item.SliderThreeTitle</td>
                                                            <td class="border-b dark:border-dark-5 text-theme-10"><a asp-area="Admin" asp-controller="LayoutSetup" asp-action="Edit" asp-route-Id="@item.Id"><i data-feather="edit"></i></a></td>
                                                            <td class="border-b dark:border-dark-5 text-theme-24"><a onclick="ShowDeleteConfirmation('PostDeleteLayoutSetup(@item.Id)')"><i data-feather="trash-2"></i></a></td>
                                                        </tr>
                                                        i++;
                                                    }

                                                }
                                            </tbody>
                                        </table>
                                    </div>

                                </div>

                            </div>
                        </div>

                    </div>

                </div>*@

        </div>

        <div class="intro-y box p-5 mt-6">
            <div class="overflow-x-auto scrollbar-hidden">
                <input id="Layout" value="@ViewBag.LayOut" hidden />
                <div id="tabulatorLayOut"></div>
            </div>
        </div>
    </div>

}
else
{
    <div class="intro-y  py-10 sm:py-20 ">
        <div class="px-5 ">
            <div class="font-medium text-center text-lg">There is no data to show</div>
        </div>
    </div>

}

<script src="../../lib/jquery/jquery.min.js"></script>
<script type="text/javascript" src="https://unpkg.com/tabulator-tables@4.1.4/dist/js/tabulator.min.js"></script>
<script src="~/dist/js/CustomJs/Delete.js"></script>
<script src="~/dist/js/LayOutSetUp.js"></script>