DeVeeraApp/Controllers/LessonController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CRM.Services;
using DeVeeraApp.ViewModels;
using DeVeeraApp.Utils;
using ErrorViewModel = DeVeeraApp.Models.ErrorViewModel;
using CRM.Core;
using CRM.Services.Authentication;
using Microsoft.AspNetCore.Http;

using CRM.Services.VideoModules;
using CRM.Services.Users;
using CRM.Core.Domain.VideoModules;
using CRM.Services.DashboardQuotes;
using CRM.Services.Settings;
using CRM.Core.Domain;
using CRM.Services.Likes;

namespace DeVeeraApp.Controllers
{


    public class LessonController : BaseController
    {
        #region fields
        private readonly ILogger<LessonController> _logger;
        private readonly ILevelServices _levelServices;
        private readonly IVideoMasterService _videoMasterService;
        private readonly IImageMasterService _imageMasterService;
        private readonly IModuleService _moduleServices;
        private readonly IS3BucketService _s3BucketService;
        private readonly IUserService _userService;
        private readonly IWorkContext _workContext;
        private readonly ILevelImageListServices _levelImageListServices;
        private readonly IModuleImageListService _moduleImageListService;
        private readonly IDiaryMasterService _diaryMasterService;
        private readonly IDashboardQuoteService _dashboardQuoteService;
        private readonly ILocalStringResourcesServices _localStringResourcesServices;
        private readonly ISettingService _settingService;
        private readonly ILikesService _likesService;
        #endregion


        #region ctor
        public LessonController(ILogger<LessonController> logger,
                                ILevelServices levelServices,
                                IVideoMasterService videoMasterService,
                                IImageMasterService imageMasterService,
                                IModuleService moduleService,
                                IS3BucketService s3BucketService,
                                IUserService userService,
                                IDashboardQuoteService dashboardQuoteService,
                                IWorkContext workContext,
                                IHttpContextAccessor httpContextAccessor,
                                IAuthenticationService authenticationService,
                                ILevelImageListServices levelImageListServices,
                                IModuleImageListService moduleImageListService,
                                IDiaryMasterService diaryMasterService,
                                        ISettingService settingService,
                                        ILikesService likesService,
                                ILocalStringResourcesServices localStringResourcesServices) : base(workContext: workContext,
                                                                                  httpContextAccessor: httpContextAccessor,
                                                                                  authenticationService: authenticationService)
        {
            _logger = logger;
            _levelServices = levelServices;
            _videoMasterService = videoMasterService;
            _imageMasterService = imageMasterService;
            _moduleServices = moduleService;
            _s3BucketService = s3BucketService;
            _userService = userService;
            _workContext = workContext;
            _levelImageListServices = levelImageListServices;
            _moduleImageListService = moduleImageListService;
            _diaryMasterService = diaryMasterService;
            _dashboardQuoteService = dashboardQuoteService;
            _localStringResourcesServices = localStringResourcesServices;
            _settingService = settingService;
            _likesService = likesService;

        }

        #endregion

        #region Utilities     
        public bool IsUserFirstLoginOnDay(DateTime? lastLoginDateUtc)
        {
            var currentUser = _userService.GetUserById(_workContext.CurrentUser.Id);

            var currentDate = DateTime.UtcNow.ToShortDateString();

            //var lastLoginDate = currentUser.LastLoginDateUtc.ToString();

            if (currentUser.UserRole.Name != "Admin")
            {
                if (lastLoginDateUtc != null && currentDate != lastLoginDateUtc.Value.ToShortDateString())
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            else
            {
                return false;
            }

        }
        #endregion

        #region Method
        public IActionResult Index(int levelno, DateTime? lastLoginDateUtc, int QuoteType, string Lang)
        {
            var random = new Random();
            var ch = TempData["LangaugeId"];
            var AllLevels = _levelServices.GetAllLevels().ToList();

            ViewBag.TotalLevels = AllLevels.Count;
            var videoData = new LevelModel
            {
                SelectedImages = new List<SelectedImage>()
            };
            AddBreadcrumbs("Level", "Index", $"/Lesson/Index/{levelno}", $"/Lesson/Index/{levelno}");
            var result = IsUserFirstLoginOnDay(lastLoginDateUtc);
            if (result == true)
            {
                return RedirectToAction("AskHappynessLevel", "Home");
            }
            var data = _levelServices.GetLevelByLevelNo(levelno);
            var currentUser = _userService.GetUserById(_workContext.CurrentUser.Id);
            var userLanguage = _settingService.GetAllSetting().Where(s => s.UserId == currentUser.Id).FirstOrDefault();
            var imagesRecord = _imageMasterService.GetImageById(data?.BannerImageId);
            if (userLanguage!=null) { 
            if (userLanguage.LanguageId == 5)
            {
                videoData.BannerImageUrl = imagesRecord?.SpanishImageUrl != null ? imagesRecord?.SpanishImageUrl : imagesRecord?.ImageUrl;
            }
            else
            {
                videoData.BannerImageUrl = imagesRecord?.ImageUrl != null ? imagesRecord?.ImageUrl : imagesRecord?.SpanishImageUrl;
            }
            }
            if (Lang != null)
            {
                if (Lang == "English")
                    userLanguage.LanguageId = 3;
                if (Lang == "Spanish")
                    userLanguage.LanguageId = 5;
            }

            var imagesRecord1 = _imageMasterService.GetImageById(data?.VideoThumbImageId);
            if (userLanguage.LanguageId == 5)
            {
                videoData.VideoThumbImageUrl = imagesRecord1?.SpanishImageUrl != null ? imagesRecord1?.SpanishImageUrl : imagesRecord1?.ImageUrl;
            }
            else
            {
                videoData.VideoThumbImageUrl = imagesRecord1?.ImageUrl != null ? imagesRecord1?.ImageUrl : imagesRecord1?.SpanishImageUrl;
            }
            var imagesRecord2 = _imageMasterService.GetImageById(data?.ShareBackgroundImageId);
            if (userLanguage?.LanguageId == 5)
            {
                videoData.ShareBackgroundImageUrl = imagesRecord2?.SpanishImageUrl != null ? imagesRecord2?.SpanishImageUrl : imagesRecord2?.ImageUrl;
            }
            else
            {
                videoData.ShareBackgroundImageUrl = imagesRecord2?.ImageUrl != null ? imagesRecord2?.ImageUrl : imagesRecord2?.SpanishImageUrl;
            }

            if (data?.VideoId != null)
            {
                var videoRecord = _videoMasterService.GetVideoById((int)data?.VideoId);

                var videoUrl = _s3BucketService.GetPreSignedURL(videoRecord?.Key);

                videoRecord.VideoUrl = videoUrl;

                _videoMasterService.UpdateVideo(videoRecord);
                videoData.VideoId = data.VideoId;
            }
            var updatedVideoData = _levelServices.GetLevelByLevelNo(levelno);
            if (updatedVideoData != null)
            {
                videoData.Id = updatedVideoData.Id;
            }
            if (userLanguage != null)
            {
                if (userLanguage.LanguageId == 5)
                {
                    videoData.FullDescription = _localStringResourcesServices.GetResourceValueByResourceName(updatedVideoData?.FullDescription);

                }
                else
                {
                    videoData.FullDescription = updatedVideoData?.FullDescription;
                }
            }
            else if (_workContext.CurrentUser.UserRole.Name == "User")
            {
                videoData.FullDescription = updatedVideoData?.FullDescription;
            }
            else if (_workContext.CurrentUser.UserRole.Name == "Admin")
            {
                videoData.FullDescription = updatedVideoData?.FullDescription;
            }
            videoData.Video = updatedVideoData?.Video;
            videoData.Subtitle = updatedVideoData?.Subtitle;
            videoData.Title = updatedVideoData?.Title;


            var likesdata = _likesService.GetAllLikes().Where(a => a.UserId == currentUser.Id && a.LevelId == (data?.Id == null ? 1 : data.Id)).ToList();
            if (likesdata.Count() != 0)
            {
                videoData.IsLike = likesdata[0].IsLike;
                videoData.IsDisLike = likesdata[0].IsDisLike;
                //videoData.Comments = likesdata[0].Comments;
            }
            videoData.LevelNo = updatedVideoData?.LevelNo;

            videoData.LikeComments = likesdata;
            foreach (var com in videoData.LikeComments)
            {
                videoData.CreatedOn = com.CreatedDate;
            }

            var quoteListlevel = _dashboardQuoteService.GetAllDashboardQuotes().Where(a => a.IsRandom == true && a.LevelId == videoData.LevelNo).ToList().FirstOrDefault();

DeVeeraApp/Controllers/UploadVideoController.cs
using CRM.Core;
using CRM.Core.Domain;
using CRM.Services;
using CRM.Services.Authentication;
using CRM.Services.Message;
using DeVeeraApp.Utils;
using DeVeeraApp.ViewModels;
using DeVeeraApp.ViewModels.Common;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DeVeeraApp.Controllers
{
    public class UploadVideoController : BaseController
    {
        #region fields

        private readonly IWeeklyUpdateServices _weeklyVideoServices;
        private readonly IVideoServices _videoServices;
        private readonly INotificationService _notificationService;


        #endregion


        #region ctor
        public UploadVideoController(IWeeklyUpdateServices weeklyVideoServices,
                                     IVideoServices videoServices,
                                     IWorkContext workContext,
                                     IHttpContextAccessor httpContextAccessor,
                                     IAuthenticationService authenticationService,
                                     INotificationService notificationService) : base(workContext: workContext,
                                                                                  httpContextAccessor: httpContextAccessor,
                                                                                  authenticationService: authenticationService)
        {
            _weeklyVideoServices = weeklyVideoServices;
            _videoServices = videoServices;
            _notificationService = notificationService;
        }
        #endregion


        #region Methods
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult Create()
        {
            AddBreadcrumbs("Level", "Create", "/UploadVideo/List", "/UploadVideo/Create");

            return View();
        }

        [HttpPost]
        public IActionResult Create(VideoModel model)
        {
            AddBreadcrumbs("Level", "Create", "/UploadVideo/List", "/UploadVideo/Create");

            if (ModelState.IsValid)
            {
                var data = model.ToEntity<Video>();
                _videoServices.InsertVideo(data);
                _notificationService.SuccessNotification("New video lesson has been created successfully.");
                return RedirectToAction("List");
            }
            return View();
        }

        public IActionResult List()
        {
            AddBreadcrumbs("Level", "List", "/UploadVideo/List", "/UploadVideo/List");

            var model = new List<VideoModel>();
            var data = _videoServices.GetAllVideos();
            if(data.Count() != 0)
            {
                foreach(var item in data)
                {
                    model.Add(item.ToModel<VideoModel>());
                }
                return View(model);
            }
            return RedirectToAction("Index", "Home");

        }

        public IActionResult Edit(int id)
        {
            AddBreadcrumbs("Level", "Edit", "/UploadVideo/List", $"/UploadVideo/Edit/{id}");

            if (id != 0)
            {
                var data = _videoServices.GetVideoById(id);
                var model = data.ToModel<VideoModel>();
                return View(model);
            }
            return RedirectToAction("List");

        }

        [HttpPost]
        public IActionResult Edit(VideoModel model)
        {
            AddBreadcrumbs("Level", "Edit", "/UploadVideo/List", $"/UploadVideo/Edit/{model.Id}");

            if (ModelState.IsValid)
            {
                var data = model.ToEntity<Video>();
                _videoServices.UpdateVideo(data);
                _notificationService.SuccessNotification("video lesson has been edited successfully.");

                return RedirectToAction("Index", "Home");
            }
            return View();
        }


        public IActionResult Delete(int videoId)
        {
           
            ResponseModel response = new ResponseModel();

            if (videoId != 0)
            {
                var videoData = _videoServices.GetVideoById(videoId);
                if (videoData == null)
                {
                    response.Success = false;
                    response.Message = "No user found";
                }
                _videoServices.DeleteVideo(videoData);

                response.Success = true;
            }
            else
            {
                response.Success = false;
                response.Message = "videoId is 0";

            }
            return Json(response);
        }


        #endregion
    }
}

DeVeeraApp/Areas/Admin/Views/Home/ExistingUser.cshtml
@model DeVeeraApp.ViewModels.WeeklyUpdateModel

@{
    ViewData["Title"] = "ExistingUser";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en" class="light">
<head>
    <meta charset="utf-8">
    <link href="dist/images/logo.svg" rel="shortcut icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Midone admin is super flexible, powerful, clean & modern responsive tailwind admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Midone admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="LEFT4CODE">
    <title>Existing User</title>
    <link rel="stylesheet" href="~/dist/css/app.css" />
</head>

<body class="main">
    <div class="container">
        <div class="error-page flex flex-col lg:flex-row items-center justify-center h-screen text-center lg:text-left">
            <div class="-intro-x ">
                @if (Model != null)
                {
                    <div class="grid grid-cols-12 gap-6 mt-5">
                        <div class="intro-y col-span-12 lg:col-span-6">
                            @{string src = Model.VideoUrl;}

                            <video src="@Url.Content(src)" controls style="width:100%; height:400px" loop />
                        </div>
                        <div class="intro-y col-span-12 lg:col-span-6">
                            <div class="text-white mt-10 lg:mt-0">
                                <div class="intro-x text-xl lg:text-3xl font-medium mt-5"> @T(Model.Title) </div>
                                <div class="intro-x text-xl lg:text-3xl font-medium mt-5">@T("Let's continue")</div>
                                <div class="intro-x text-lg mt-3">@T(Model.Subtitle)</div>
                                @if (ViewBag.SrNo != 0)
                                {
                                    <a asp-controller="Lesson" asp-action="Index" asp-route-srno="@ViewBag.SrNo" asp-route-id="@Model.LastLevel" asp-route-lastLoginDateUtc="@ViewBag.LastLoginDateUtc" class="intro-x btn py-3 px-4 text-white border-white dark:border-dark-5 dark:text-gray-300 mt-10">@T("Let's Start")</a>

                                }
                                else
                                {
                                    <a asp-controller="home" asp-action="Index" class="intro-x btn py-3 px-4 text-white border-white dark:border-dark-5 dark:text-gray-300 mt-10">Dashboard</a>

                                }
                            </div>

                        </div>
                    </div>

                }
                else
                {
                    <div class="intro-y col-span-12 lg:col-span-6">
                        <div class="text-white mt-10 lg:mt-0">
                            <div class="intro-x text-xl lg:text-3xl font-medium mt-5">@T("Sorry, There is no data.") </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBG7gNHAhDzgYmq4-EHvM4bqW1DNj2UCuk&amp;libraries=places"></script>
    <script src="dist/js/app.js"></script>

</body>
</html>

DeVeeraApp/Areas/Admin/Views/Home/FeelGoodStories.cshtml
@model IList<DeVeeraApp.ViewModels.FeelGoodStoryModel>

@{
    ViewData["Title"] = "Feel Good Stories";

}

<div class="intro-y flex flex-col sm:flex-row items-center mt-8">
    <h2 class="text-lg font-medium mr-auto">
        Feel Good Stories
    </h2>
</div>
<div class="border-t border-theme-25">

    <div class="intro-y grid grid-cols-12 gap-6 mt-5">

        @if (Model.Count != 0)
        {

            @foreach (var item in Model)
            {
                <!-- BEGIN: Blog Layout -->
                <div class="intro-y blog col-span-12 md:col-span-6 box">
                    <div class="blog__preview image-fit">
                        @{var smallImg = (item.Image?.ImageUrl == null) ? "/dist/images/profile-14.jpg" : item.Image.ImageUrl;}
                        <img class="rounded-t-md" src="@smallImg">
                        <div class="absolute w-full flex items-center px-5 pt-6 z-10">
                            <div class="w-10 h-10 flex-none image-fit">
                                @{var largeImg = (item.Image?.ImageUrl == null) ? "/dist/images/preview-4.jpg" : item.Image.ImageUrl;}
                                <img class="rounded-full" src="@largeImg">
                            </div>
                            <div class="ml-3 text-white mr-auto">
                                <a href="" class="font-medium">@T(item.Author)</a>
                                <div class="text-xs mt-0.5">@T("29 minutes ago")</div>
                            </div>

                        </div>
                        <div class="absolute bottom-0 text-white px-5 pb-6 z-10">

                            <a href="" class="block font-medium text-xl mt-3">@T(item.Title)</a>
                        </div>
                    </div>
                    <div class="p-5 text-gray-700 dark:text-gray-600">@Html.Raw(item.Story)</div>

                </div>
            }


        }
        else
        {
            <h2 class="text-lg font-medium mr-auto">
                There are no stories yet.
            </h2>
        }
    </div>
</div>

DeVeeraApp/Areas/Admin/Views/Home/Help.cshtml
@{
    ViewData["Title"] = "Help";
    Layout = null;
}

<!DOCTYPE html>
<!--
Template Name: Icewall - HTML Admin Dashboard Template
Author: Left4code
Website: http://www.left4code.com/
Contact: muhammadrizki@left4code.com
Purchase: https://themeforest.net/user/left4code/portfolio
Renew Support: https://themeforest.net/user/left4code/portfolio
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<html lang="en" class="light">
<!-- BEGIN: Head -->
<head>
    <meta charset="utf-8">
    <link href="~/dist/images/logo.svg" rel="shortcut icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Icewall admin is super flexible, powerful, clean & modern responsive tailwind admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Icewall Admin Template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="LEFT4CODE">
    <title>Dashboard - Icewall - Tailwind HTML Admin Template</title>
    <!-- BEGIN: CSS Assets-->
    <link rel="stylesheet" href="~/dist/css/app.css" />
    <!-- END: CSS Assets-->
</head>
<!-- END: Head -->
<body class="main">
    <div class="container">
        <!-- BEGIN: Error Page -->
        <div class="error-page flex flex-col lg:flex-row  justify-center h-screen text-center lg:text-left">

            <div class="text-white mt-10 lg:mt-0">
                <div class="intro-x text-8xl font-medium">@T("Help Page")</div>
                <div class="intro-x text-xl lg:text-3xl font-medium mt-5"></div>
                <div class="intro-x text-lg mt-3"></div>
                <a asp-controller="Home" asp-action="Index" class="intro-x btn py-3 px-4 text-white border-white dark:border-dark-5 dark:text-gray-300 mt-10">Back to Home</a>
            </div>
           
        </div>

       
        <!-- END: Error Page -->
    </div>

    <!-- BEGIN: JS Assets-->
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=[" your-google-map-api"]&libraries=places"></script>
    <script src="~/dist/js/app.js"></script>
    <!-- END: JS Assets-->
</body>
</html>

DeVeeraApp/Areas/Admin/Views/Home/List.cshtml
@model List<DeVeeraApp.ViewModels.LayoutSetups.LayoutSetupModel>
    @{
    ViewData["Title"] = "List";
    }


    @if (@ViewBag.LayOut != null)
    {
    <div class="intro-y  py-10 sm:py-20 ">
        <div class="px-5 ">
            <div class="font-medium text-center text-lg"> Home Page List</div>
            <div class="text-gray-600 text-center mt-2">Below are the Home Page List.</div>
        </div>

        <div class="px-5 sm:px-20  border-t border-gray-200 dark:border-dark-5">
            <div class="grid grid-cols-12 mt-6">
                <div class="intro-y col-span-12 text-right">
                    <a asp-controller="Home" asp-action="Create" class="btn btn-primary w-28"><i data-feather="plus" class="mr-2 w-5 h-5"></i>Create</a>
                </div>
            </div>
           @*<div class="grid grid-cols-12 gap-4 gap-y-5 mt-6">
                <div class="intro-y box p-5 col-span-12">
                    <div class="intro-y">

                        <div class="p-5" id="basic-table">
                            <div class="preview">
                                <div class="overflow-x-auto">
                                    <table class="table">
                                        <thead>
                                            <tr>
                                                <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">#</th>
                                                <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Title 1</th>
                                                <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Title 2</th>
                                                <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Title 3</th>
                                                <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Edit</th>
                                                <th class="border-b-2 dark:border-dark-5 whitespace-nowrap">Delete</th>

                                            </tr>
                                        </thead>
                                        <tbody>
                                            @{
                                            int i = 1;
                                            foreach (var item in Model)
                                            {
                                            <tr>
                                                <td class="border-b dark:border-dark-5">@i</td>
                                                <td class="border-b dark:border-dark-5">@item.SliderOneTitle</td>
                                                <td class="border-b dark:border-dark-5">@item.SliderTwoTitle</td>
                                                <td class="border-b dark:border-dark-5">@item.SliderThreeTitle</td>
                                                <td class="border-b dark:border-dark-5 text-theme-10"><a asp-area="Admin" asp-controller="LayoutSetup" asp-action="Edit" asp-route-Id="@item.Id"><i data-feather="edit"></i></a></td>
                                                <td class="border-b dark:border-dark-5 text-theme-24"><a onclick="ShowDeleteConfirmation('PostDeleteLayoutSetup(@item.Id)')"><i data-feather="trash-2"></i></a></td>
                                            </tr>
                                            i++;
                                            }

                                            }
                                        </tbody>
                                    </table>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>

            </div>*@

        </div>

        <div class="intro-y box p-5 mt-6">
            <div class="overflow-x-auto scrollbar-hidden">
                <input id="Home" value="@ViewBag.LayOut" hidden />
                <div id="tabulatorLayOut"></div>
            </div>
        </div>
    </div>

    }
    else
    {
    <div class="intro-y  py-10 sm:py-20 ">
        <div class="px-5 ">
            <div class="font-medium text-center text-lg">There is no data to show</div>
        </div>
    </div>

    }

    <script src="../../lib/jquery/jquery.min.js"></script>
    <script type="text/javascript" src="https://unpkg.com/tabulator-tables/dist/js/tabulator.min.js"></script>
    <script src="~/dist/js/CustomJs/Delete.js"></script>
    <script src="~/dist/js/Home.js"></script>

DeVeeraApp/Areas/Admin/Views/Home/NewUser.cshtml
@model DeVeeraApp.ViewModels.WeeklyUpdateModel
@{
    ViewData["Title"] = "NewUser";
    Layout = null;
}

<!DOCTYPE html>
<!--
Template Name: Midone - HTML Admin Dashboard Template
Author: Left4code
Website: http://www.left4code.com/
Contact: muhammadrizki@left4code.com
Purchase: https://themeforest.net/user/left4code/portfolio
Renew Support: https://themeforest.net/user/left4code/portfolio
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<html lang="en" class="light">
<!-- BEGIN: Head -->
<head>
    <meta charset="utf-8">
    <link href="dist/images/logo.svg" rel="shortcut icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Midone admin is super flexible, powerful, clean & modern responsive tailwind admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Midone admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="LEFT4CODE">
    <title>New User</title>
    <!-- BEGIN: CSS Assets-->
    <link rel="stylesheet" href="~/dist/css/app.css" />
    <!-- END: CSS Assets-->
</head>
<body class="main">
    <div class="container">
        <div class="error-page flex flex-col lg:flex-row items-center justify-center h-screen text-center lg:text-left">
            <div class="-intro-x ">
                @if (Model != null)
                {
                    <div class="grid grid-cols-12 gap-6 mt-5">
                        <div class="intro-y col-span-12 lg:col-span-6">
                            @{string src = Model.VideoUrl;}
                            <video src="@Url.Content(src)" controls style="width:100%; height:400px" loop />
                        </div>
                        <div class="intro-y col-span-12 lg:col-span-6">
                            <div class="text-white mt-10 lg:mt-0">
                                <div class="intro-x text-xl lg:text-3xl font-medium mt-5"> @T(Model.Title) </div>
                                <div class="intro-x text-xl lg:text-3xl font-medium mt-5">Let's Start </div>
                                <div class="intro-x text-lg mt-3"> @T(Model.Subtitle) </div>
                                @if (Model.LastLevel != 0)
                                {
                                    @*<a asp-controller="Lesson" asp-action="Index" asp-route-srno="@ViewBag.SrNo" asp-route-id="@Model.LastLevel" class="intro-x btn py-3 px-4 text-white border-white dark:border-dark-5 dark:text-gray-300 mt-10">Let's Start</a>*@
                                    <a asp-controller="Diary" asp-action="AskUserEmotion" class="intro-x btn py-3 px-4 text-white border-white dark:border-dark-5 dark:text-gray-300 mt-10">@T("Let's Start")</a>
                                }
                                else
                                {
                                    @*<a asp-controller="Home" asp-action="Index" class="intro-x btn py-3 px-4 text-white border-white dark:border-dark-5 dark:text-gray-300 mt-10">Dashboard</a>*@
                            <a asp-controller="Diary" asp-action="AskUserEmotion" class="intro-x btn py-3 px-4 text-white border-white dark:border-dark-5 dark:text-gray-300 mt-10">@T("Let's Start")</a>

                                }
                            </div>

                        </div>
                    </div>

                }
                else
                {
                    <div class="intro-y col-span-12 lg:col-span-6">
                        <div class="text-white mt-10 lg:mt-0">
                            <div class="intro-x text-xl lg:text-3xl font-medium mt-5">@T("Sorry, There is no data.") </div>
                        </div>
                    </div>
                }

            </div>
        </div>
    </div>
    <script src="https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/markerclusterer.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBG7gNHAhDzgYmq4-EHvM4bqW1DNj2UCuk&amp;libraries=places"></script>
    <script src="dist/js/app.js"></script>

</body>

</html>